### ISSUE TITLE
[ACELL03] Examples cannot be in headless mode without Serial

### ISSUE THREAD

**Issue by aliphys** [arduino-libraries/Arduino_Cellular#20]
The Serial monitor, together with the `.setDebugStream(Serial)` option provided in the Arduino_Cellular library, provides additional information on the sketch as it is executed. This can be useful for understanding/debugging the sketch by users without relying on an external JTAG interface.

Given that the Arduino_Cellular library is designed to be used with the Portenta C33/H7 (See https://github.com/arduino-libraries/Arduino_Cellular/issues/18) as a standalone device, the examples should also be usable in headless mode (with the `while (!Serial);` line commented). To this end, LED indicators (e.g. `digitalWrite(LRED, HIGH)`) should be used on the following sketches.
- [ ] [DeleteSMS](https://github.com/arduino-libraries/Arduino_Cellular/tree/main/examples/DeleteSMS)
- [ ] [GetLocation](https://github.com/arduino-libraries/Arduino_Cellular/tree/main/examples/GetLocation)
- [ ] [GetTime](https://github.com/arduino-libraries/Arduino_Cellular/tree/main/examples/GetTime)
- [ ] [HTTPClient](https://github.com/arduino-libraries/Arduino_Cellular/tree/main/examples/HTTPClient)
- [ ] [HTTPSClient](https://github.com/arduino-libraries/Arduino_Cellular/tree/main/examples/HTTPSClient)
- [ ] [ModemTerminal](https://github.com/arduino-libraries/Arduino_Cellular/tree/main/examples/ModemTerminal)
- [ ] [ReceiveSMS](https://github.com/arduino-libraries/Arduino_Cellular/tree/main/examples/ReceiveSMS)
- [ ] [SendSMS](https://github.com/arduino-libraries/Arduino_Cellular/tree/main/examples/SendSMS)

**Comment by sebromero** [comment]
I'd argue that the examples are meant to be used in combination with Serial to understand clearly what's happening in the code. Removing the need for Serial in a production sketch can be left as an exercise to the user.
